extensions:
  ecs_observer:
    refresh_interval: 15s
    cluster_name: 'aoc-ecs'
    cluster_region: 'us-west-2'
    sd_result_file: '/etc/ecs_sd_targets.yaml'
    # docker_label:
    #   job_name_label: 'ECS_PROMETHEUS_JOB_NAME'
    #   metrics_path_label: 'ECS_PROMETHEUS_METRICS_PATH'
    #   port_label: 'ECS_PROMETHEUS_EXPORTER_PORT_SUBSET_A'
    task_definitions:
    - job_name: 'task_def_1'
      metrics_path: '/metrics'
      metrics_ports: '9113;5678'
      task_definition_arn_pattern: '.*:task-definition/aoc-ec2-nginx:[0-9]+'

receivers:
  receiver_creator:
    watch_observers: [ecs_observer]
    receivers:
      prometheus_simple:
        rule: type.task
        config:
          metrics_path: '`metricsPath`'
  prometheus:
    config:
      scrape_configs:
      - job_name: "task_def_1"
        file_sd_configs:
        - files:
          - '/etc/ecs_sd_targets.yaml'

exporters:
  awsemf:
    log_group_name: 'awscollector-test'
    region: 'us-west-2'
    log_stream_name: ecs-sd
    dimension_rollup_option: 'NoDimensionRollup'

service:
  pipelines:
    metrics:
      receivers: [receiver_creator]
      exporters: [awsemf]

  extensions: [ecs_observer]
